name: Fedora Latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./.docker/Dockerfile.fedora.latest --tag albert-x-window-switcher-fedora-latest:$(date +%s)